#!/bin/bash

if [[ -z "$1" ]]; then
	echo "Please supply version number"
	exit
else
	VERSION=$1
fi

function cleanup(){
	# Remove stale wine sockets
	rm -rf /tmp/.wine-*
}

cleanup

SOURCEDIR=/opt/wine-electrum/drive_c/electrum-frc/Electrum-frc-$VERSION


cd $SOURCEDIR

$PYTHON "C:/PyInstaller/pyinstaller.py" -y "C:/electrum-frc/deterministic.spec"
cp /opt/wine-electrum/drive_c/electrum-frc/electrum-frc.nsi $SOURCEDIR/

echo "Running c:/electrum-frc/Electrum-frc-$VERSION/electrum-frc.nsi for install"
xvfb-run wine c:\\"Program Files (x86)"\\NSIS\\makensis.exe -V1 c:/electrum-frc/Electrum-frc-$VERSION/electrum-frc.nsi


cleanup
